# Generated by Django 5.1 on 2024-09-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_ordercartitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_factory_ready',
        ),
    ]
