# Generated by Django 5.0 on 2024-03-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_order_ordercartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'DRAFT'), (1, 'Sifariş qeydə olundu'), (2, 'Sifarişi Anbar qəbul etdi'), (3, 'Sifariş hazırlanır')], default=0),
        ),
    ]
