# Generated by Django 5.0 on 2024-03-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'DRAFT'), (1, 'Sifariş qeydə olundu'), (2, 'Sifarişi Anbar qəbul etdi'), (3, 'Sifariş hazırlanır'), (4, 'Məhsullar hazırdır'), (5, 'Geri Qayıtma'), (6, 'Məhsullar yoldadır'), (7, 'Məhsullar çatdırıldı'), (8, 'Satış tamamlandı')], default=0),
        ),
    ]
