# Generated by Django 5.1 on 2024-09-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercartitem',
            name='size',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
