# Generated by Django 5.0 on 2024-04-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_ordercartitem_size_orderitem_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="install_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
