# Generated by Django 5.0 on 2024-04-04 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_driver_share_order_worker_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Expense',
                'verbose_name_plural': 'Order Expenses',
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
    ]
