# Generated by Django 5.0 on 2024-04-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_factory_ready',
            field=models.BooleanField(default=False),
        ),
    ]
