# Generated by Django 5.0 on 2024-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderitem_is_factory_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'DRAFT'), (1, 'Satış qeydə alındı'), (2, 'Anbar satışı qəbul etdi'), (3, 'Məhsullar hazırlanır'), (4, 'Məhsullar hazırdır'), (5, 'Geri Qayıtma'), (6, 'Məhsullar yoldadır'), (7, 'Məhsullar çatdırıldı'), (8, 'Satış tamamlandı')], default=0),
        ),
    ]
