services:
  app:
    <<: &app
      image: ${PROJECT_NAME}:prod
      container_name: ${PROJECT_NAME}_app_prod
      build:
        args:
          - DJANGO_ENV=prod
      command: bash ./docker/app/production/start.sh
      volumes:
        - ./staticfiles:/var/www/static:rw
        - ./media:/var/www/media:rw
      environment:
        - DJANGO_ENV=prod
