services:
  app:
    <<: &app
      image: ${PROJECT_NAME}:dev
      container_name: ${PROJECT_NAME}_app_dev
      build:
        args:
          - DJANGO_ENV=dev
      environment:
        - DJANGO_ENV=dev
