# Generated by Django 5.0 on 2024-03-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplierpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierPayment',
        ),
    ]
