# Generated by Django 5.0 on 2024-03-23 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_sale', '0001_initial'),
        ('factory_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorySaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='factory_sale.factorysale')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='factory_storage.factorystorageitem')),
            ],
            options={
                'verbose_name': 'FactorySaleItem',
                'verbose_name_plural': 'FactorySaleItems',
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
    ]
